//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1 版自动生成。
// 
#pragma warning disable 1591

namespace THOK.WCS.Bll.MdjInspurWmsService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LwmWarehouseWorkServiceSoapBinding", Namespace="http://10.56.192.104:9081/lwm/axis/LwmWarehouseWorkService")]
    public partial class LwmWarehouseWorkServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback lwmStroeInProgFeedbackOperationCompleted;
        
        private System.Threading.SendOrPostCallback lwmStoreInCompleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback lwmStoreOutProgFeedbackOperationCompleted;
        
        private System.Threading.SendOrPostCallback lwmStoreOutCompleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LwmWarehouseWorkServiceService() {
            this.Url = global::THOK.WCS.Bll.Properties.Settings.Default.THOK_WCS_Bll_MdjInspurWmsService_LwmWarehouseWorkServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event lwmStroeInProgFeedbackCompletedEventHandler lwmStroeInProgFeedbackCompleted;
        
        /// <remarks/>
        public event lwmStoreInCompleteCompletedEventHandler lwmStoreInCompleteCompleted;
        
        /// <remarks/>
        public event lwmStoreOutProgFeedbackCompletedEventHandler lwmStoreOutProgFeedbackCompleted;
        
        /// <remarks/>
        public event lwmStoreOutCompleteCompletedEventHandler lwmStoreOutCompleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://warehouseservice.mdj.online.itfc.lwm.v6.com", ResponseNamespace="http://10.56.192.104:9081/lwm/axis/LwmWarehouseWorkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("lwmStroeInProgFeedbackReturn")]
        public string lwmStroeInProgFeedback(string inXml) {
            object[] results = this.Invoke("lwmStroeInProgFeedback", new object[] {
                        inXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void lwmStroeInProgFeedbackAsync(string inXml) {
            this.lwmStroeInProgFeedbackAsync(inXml, null);
        }
        
        /// <remarks/>
        public void lwmStroeInProgFeedbackAsync(string inXml, object userState) {
            if ((this.lwmStroeInProgFeedbackOperationCompleted == null)) {
                this.lwmStroeInProgFeedbackOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlwmStroeInProgFeedbackOperationCompleted);
            }
            this.InvokeAsync("lwmStroeInProgFeedback", new object[] {
                        inXml}, this.lwmStroeInProgFeedbackOperationCompleted, userState);
        }
        
        private void OnlwmStroeInProgFeedbackOperationCompleted(object arg) {
            if ((this.lwmStroeInProgFeedbackCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.lwmStroeInProgFeedbackCompleted(this, new lwmStroeInProgFeedbackCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://warehouseservice.mdj.online.itfc.lwm.v6.com", ResponseNamespace="http://10.56.192.104:9081/lwm/axis/LwmWarehouseWorkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("lwmStoreInCompleteReturn")]
        public string lwmStoreInComplete(string inXml) {
            object[] results = this.Invoke("lwmStoreInComplete", new object[] {
                        inXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void lwmStoreInCompleteAsync(string inXml) {
            this.lwmStoreInCompleteAsync(inXml, null);
        }
        
        /// <remarks/>
        public void lwmStoreInCompleteAsync(string inXml, object userState) {
            if ((this.lwmStoreInCompleteOperationCompleted == null)) {
                this.lwmStoreInCompleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlwmStoreInCompleteOperationCompleted);
            }
            this.InvokeAsync("lwmStoreInComplete", new object[] {
                        inXml}, this.lwmStoreInCompleteOperationCompleted, userState);
        }
        
        private void OnlwmStoreInCompleteOperationCompleted(object arg) {
            if ((this.lwmStoreInCompleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.lwmStoreInCompleteCompleted(this, new lwmStoreInCompleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://warehouseservice.mdj.online.itfc.lwm.v6.com", ResponseNamespace="http://10.56.192.104:9081/lwm/axis/LwmWarehouseWorkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("lwmStoreOutProgFeedbackReturn")]
        public string lwmStoreOutProgFeedback(string inXml) {
            object[] results = this.Invoke("lwmStoreOutProgFeedback", new object[] {
                        inXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void lwmStoreOutProgFeedbackAsync(string inXml) {
            this.lwmStoreOutProgFeedbackAsync(inXml, null);
        }
        
        /// <remarks/>
        public void lwmStoreOutProgFeedbackAsync(string inXml, object userState) {
            if ((this.lwmStoreOutProgFeedbackOperationCompleted == null)) {
                this.lwmStoreOutProgFeedbackOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlwmStoreOutProgFeedbackOperationCompleted);
            }
            this.InvokeAsync("lwmStoreOutProgFeedback", new object[] {
                        inXml}, this.lwmStoreOutProgFeedbackOperationCompleted, userState);
        }
        
        private void OnlwmStoreOutProgFeedbackOperationCompleted(object arg) {
            if ((this.lwmStoreOutProgFeedbackCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.lwmStoreOutProgFeedbackCompleted(this, new lwmStoreOutProgFeedbackCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://warehouseservice.mdj.online.itfc.lwm.v6.com", ResponseNamespace="http://10.56.192.104:9081/lwm/axis/LwmWarehouseWorkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("lwmStoreOutCompleteReturn")]
        public string lwmStoreOutComplete(string inXml) {
            object[] results = this.Invoke("lwmStoreOutComplete", new object[] {
                        inXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void lwmStoreOutCompleteAsync(string inXml) {
            this.lwmStoreOutCompleteAsync(inXml, null);
        }
        
        /// <remarks/>
        public void lwmStoreOutCompleteAsync(string inXml, object userState) {
            if ((this.lwmStoreOutCompleteOperationCompleted == null)) {
                this.lwmStoreOutCompleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlwmStoreOutCompleteOperationCompleted);
            }
            this.InvokeAsync("lwmStoreOutComplete", new object[] {
                        inXml}, this.lwmStoreOutCompleteOperationCompleted, userState);
        }
        
        private void OnlwmStoreOutCompleteOperationCompleted(object arg) {
            if ((this.lwmStoreOutCompleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.lwmStoreOutCompleteCompleted(this, new lwmStoreOutCompleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void lwmStroeInProgFeedbackCompletedEventHandler(object sender, lwmStroeInProgFeedbackCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class lwmStroeInProgFeedbackCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal lwmStroeInProgFeedbackCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void lwmStoreInCompleteCompletedEventHandler(object sender, lwmStoreInCompleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class lwmStoreInCompleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal lwmStoreInCompleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void lwmStoreOutProgFeedbackCompletedEventHandler(object sender, lwmStoreOutProgFeedbackCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class lwmStoreOutProgFeedbackCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal lwmStoreOutProgFeedbackCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void lwmStoreOutCompleteCompletedEventHandler(object sender, lwmStoreOutCompleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class lwmStoreOutCompleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal lwmStoreOutCompleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591