// <auto-generated />
namespace THOK.Wms.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-alpha3-20222")]
    public sealed partial class modify_task_and_history_to_cellcode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modify_task_and_history_to_cellcode));
        
        string IMigrationMetadata.Id
        {
            get { return "201311180502482_modify_task_and_history_to_cellcode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
