// <auto-generated />
namespace THOK.Wms.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-alpha3-20222")]
    public sealed partial class modify_cell_add_IsMultiBrand : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modify_cell_add_IsMultiBrand));
        
        string IMigrationMetadata.Id
        {
            get { return "201308070314391_modify_cell_add_IsMultiBrand"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
