// <auto-generated />
namespace THOK.Wms.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-alpha3-20222")]
    public sealed partial class add_SortingLowerLimit_SortType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_SortingLowerLimit_SortType));
        
        string IMigrationMetadata.Id
        {
            get { return "201305240709279_add_SortingLowerLimit_SortType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
