// <auto-generated />
namespace THOK.Wms.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-alpha3-20222")]
    public sealed partial class cell_add_FirstInFirstOut_and_strage_add_StorageSequence : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cell_add_FirstInFirstOut_and_strage_add_StorageSequence));
        
        string IMigrationMetadata.Id
        {
            get { return "201309040032503_cell_add_FirstInFirstOut_and_strage_add_StorageSequence"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
